### PR TITLE
add-mock-data

### LINKED ISSUE #53: useful mock data needed
We need some mock data that looks similar to ours so that we can test our queries.

blocking #52

### PR DESCRIPTION
**Pull request by JMurphyWeb**
Add better mock data, allow different initial data by sending through the config. 

resolves #53

### CODE REVIEW

**Comment by JMurphyWeb** [comment]
@SimonLab @mk4111 thoughts?

**Comment by JMurphyWeb** [comment]
Cant work out why failing on travis. Tests passing locally.

**Comment by SimonLab** [comment]
@JMurphyWeb do we still need this PR?

**Comment by JMurphyWeb** [comment]
probably not. leave it for now. i will clean up

**Pull request merged**
